#include "stdafx.h"

#include "Common/Global/Globals.h"

#include "VM/VMMain.h"
#include "VM/ExecutionCore/Interpreter/InterpreterEECore/InterpreterEECore.h"
#include "Common/Util/EECoreInstructionUtil/EECoreInstructionUtil.h"

void InterpreterEECore::BGEZAL()
{
	// BRANCH_LINK(Rs >= 0). No exceptions.
	auto& source1Reg = getVM()->getResources()->EE->EECore->R5900->GPR[getInstruction().getIRs()];
	const s16 offset = getInstruction().getIImmS();

	if (source1Reg->readDwordS(0) >= 0)
	{
		getVM()->getResources()->EE->EECore->R5900->LinkRegister->setLinkAddress();
		;// branch; 
	}
}

void InterpreterEECore::BGEZALL()
{
	// BRANCH_LINK(Rs >= 0). No exceptions.
	auto& source1Reg = getVM()->getResources()->EE->EECore->R5900->GPR[getInstruction().getIRs()];
	const s16 offset = getInstruction().getIImmS();

	if (source1Reg->readDwordS(0) >= 0)
	{
		getVM()->getResources()->EE->EECore->R5900->LinkRegister->setLinkAddress();
		;// branch likely; 
	}
}

void InterpreterEECore::BLTZAL()
{
	// BRANCH_LINK(Rs < 0). No exceptions.
	auto& source1Reg = getVM()->getResources()->EE->EECore->R5900->GPR[getInstruction().getIRs()];
	const s16 offset = getInstruction().getIImmS();

	if (source1Reg->readDwordS(0) < 0)
	{
		getVM()->getResources()->EE->EECore->R5900->LinkRegister->setLinkAddress();
		;// branch; 
	}
}

void InterpreterEECore::BLTZALL()
{
	// BRANCH_LINK(Rs < 0). No exceptions.
	auto& source1Reg = getVM()->getResources()->EE->EECore->R5900->GPR[getInstruction().getIRs()];
	const s16 offset = getInstruction().getIImmS();

	if (source1Reg->readDwordS(0) < 0)
	{
		getVM()->getResources()->EE->EECore->R5900->LinkRegister->setLinkAddress();
		;// branch likely; 
	}
}

void InterpreterEECore::JAL()
{
	// JUMP_LINK(). No exceptions.
	getVM()->getResources()->EE->EECore->R5900->LinkRegister->setLinkAddress();
	const s32 offset = getInstruction().getJOffsetAddress();
	// branch; 
}

void InterpreterEECore::JALR()
{
	// JUMP_LINK_REGISTER(). Exceptions generated by other components.
	auto& sourceReg = getVM()->getResources()->EE->EECore->R5900->GPR[getInstruction().getRRs()];
	auto& destReg = getVM()->getResources()->EE->EECore->R5900->GPR[getInstruction().getRRd()];

	destReg->writeDwordU(0, static_cast<u64>(getVM()->getResources()->EE->EECore->R5900->PC->getPCValue() + 8));
	// branch to address in sourceReg->readWordU(0);
}
