#include "stdafx.h"

#include "Common/PS2Resources/EE/DMAC/DMAC_t.h"
#include "Common/PS2Resources/EE/DMAC/Types/DMAC_Registers_t.h"
#include "Common/PS2Resources/Types/MappedMemory/MappedMemory_t.h"
#include "Common/PS2Resources/Types/MappedMemory/DeadMMemory_t.h"

DMAC_t::DMAC_t(const PS2Resources_t* const PS2Resources) :
	PS2ResourcesSubobject(PS2Resources),
	SliceCountState{ 0 },
	ChainExitState{ false },
	ChainStackLevelState{ 0 }, 
	InterleavedSkipState{ false },
	InterleavedCountState{ 0 },

	// Registers
	DMAC_REGISTER_D0_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 0)),
	DMAC_REGISTER_D0_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D0_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_REGISTER_D0_TADR(std::make_shared<DmacRegisterTadr_t>()),
	DMAC_REGISTER_D0_ASR0(std::make_shared<DmacRegisterAsr_t>()),
	DMAC_REGISTER_D0_ASR1(std::make_shared<DmacRegisterAsr_t>()),
	DMAC_MEMORY_8060(std::make_shared<DeadMMemory_t>(0xFA0, "DMAC: DMAC_8060 (reserved)", 0x10008060)),
	DMAC_REGISTER_D1_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 1)),
	DMAC_REGISTER_D1_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D1_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_REGISTER_D1_TADR(std::make_shared<DmacRegisterTadr_t>()),
	DMAC_REGISTER_D1_ASR0(std::make_shared<DmacRegisterAsr_t>()),
	DMAC_REGISTER_D1_ASR1(std::make_shared<DmacRegisterAsr_t>()),
	DMAC_MEMORY_9060(std::make_shared<DeadMMemory_t>(0xFA0, "DMAC: DMAC_9060 (reserved)", 0x10009060)),
	DMAC_REGISTER_D2_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 2)),
	DMAC_REGISTER_D2_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D2_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_REGISTER_D2_TADR(std::make_shared<DmacRegisterTadr_t>()),
	DMAC_REGISTER_D2_ASR0(std::make_shared<DmacRegisterAsr_t>()),
	DMAC_REGISTER_D2_ASR1(std::make_shared<DmacRegisterAsr_t>()),
	DMAC_MEMORY_a060(std::make_shared<DeadMMemory_t>(0xFA0, "DMAC: DMAC_a060 (reserved)", 0x1000a060)),
	DMAC_REGISTER_D3_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 3)),
	DMAC_REGISTER_D3_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D3_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_MEMORY_b030(std::make_shared<DeadMMemory_t>(0x3D0, "DMAC: DMAC_b030 (reserved)", 0x1000b030)),
	DMAC_REGISTER_D4_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 4)),
	DMAC_REGISTER_D4_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D4_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_REGISTER_D4_TADR(std::make_shared<DmacRegisterTadr_t>()),
	DMAC_MEMORY_b440(std::make_shared<DeadMMemory_t>(0xBC0, "DMAC: DMAC_b440 (reserved)", 0x1000b440)),
	DMAC_REGISTER_D5_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 5)),
	DMAC_REGISTER_D5_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D5_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_MEMORY_c030(std::make_shared<DeadMMemory_t>(0x3D0, "DMAC: DMAC_c030 (reserved)", 0x1000c030)),
	DMAC_REGISTER_D6_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 6)),
	DMAC_REGISTER_D6_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D6_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_REGISTER_D6_TADR(std::make_shared<DmacRegisterTadr_t>()),
	DMAC_MEMORY_c440(std::make_shared<DeadMMemory_t>(0x3C0, "DMAC: DMAC_c440 (reserved)", 0x1000c440)),
	DMAC_REGISTER_D7_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 7)),
	DMAC_REGISTER_D7_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D7_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_MEMORY_c830(std::make_shared<DeadMMemory_t>(0x7D0, "DMAC: DMAC_c830 (reserved)", 0x1000c830)),
	DMAC_REGISTER_D8_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 8)),
	DMAC_REGISTER_D8_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D8_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_MEMORY_d030(std::make_shared<DeadMMemory_t>(0x50, "DMAC: DMAC_d030 (reserved)", 0x1000d030)),
	DMAC_REGISTER_D8_SADR(std::make_shared<DmacRegisterSadr_t>()),
	DMAC_MEMORY_d090(std::make_shared<DeadMMemory_t>(0x370, "DMAC: DMAC_d090 (reserved)", 0x1000d090)),
	DMAC_REGISTER_D9_CHCR(std::make_shared<DmacRegisterChcr_t>(getRootResources(), 9)),
	DMAC_REGISTER_D9_MADR(std::make_shared<DmacRegisterMadr_t>()),
	DMAC_REGISTER_D9_QWC(std::make_shared<DmacRegisterQwc_t>()),
	DMAC_REGISTER_D9_TADR(std::make_shared<DmacRegisterTadr_t>()),
	DMAC_MEMORY_d440(std::make_shared<DeadMMemory_t>(0x40, "DMAC: DMAC_d440 (reserved)", 0x1000d440)),
	DMAC_REGISTER_D9_SADR(std::make_shared<DmacRegisterSadr_t>()),
	DMAC_MEMORY_d490(std::make_shared<DeadMMemory_t>(0xB70, "DMAC: DMAC_d490 (reserved)", 0x1000d490)),
	DMAChannelRegisters{
		{ DMAC_REGISTER_D0_CHCR, DMAC_REGISTER_D0_MADR, DMAC_REGISTER_D0_QWC, DMAC_REGISTER_D0_TADR, DMAC_REGISTER_D0_ASR0, DMAC_REGISTER_D0_ASR1, nullptr,{ DMAC_REGISTER_D0_ASR0, DMAC_REGISTER_D0_ASR1 } },
		{ DMAC_REGISTER_D1_CHCR, DMAC_REGISTER_D1_MADR, DMAC_REGISTER_D1_QWC, DMAC_REGISTER_D1_TADR, DMAC_REGISTER_D1_ASR0, DMAC_REGISTER_D1_ASR1, nullptr,{ DMAC_REGISTER_D1_ASR0, DMAC_REGISTER_D1_ASR1 } },
		{ DMAC_REGISTER_D2_CHCR, DMAC_REGISTER_D2_MADR, DMAC_REGISTER_D2_QWC, DMAC_REGISTER_D2_TADR, DMAC_REGISTER_D2_ASR0, DMAC_REGISTER_D2_ASR1, nullptr,{ DMAC_REGISTER_D2_ASR0, DMAC_REGISTER_D2_ASR1 } },
		{ DMAC_REGISTER_D3_CHCR, DMAC_REGISTER_D3_MADR, DMAC_REGISTER_D3_QWC, nullptr,             nullptr,             nullptr,             nullptr,{ nullptr,             nullptr } },
		{ DMAC_REGISTER_D4_CHCR, DMAC_REGISTER_D4_MADR, DMAC_REGISTER_D4_QWC, DMAC_REGISTER_D4_TADR, nullptr,             nullptr,             nullptr,{ nullptr,             nullptr } },
		{ DMAC_REGISTER_D5_CHCR, DMAC_REGISTER_D5_MADR, DMAC_REGISTER_D5_QWC, nullptr,             nullptr,             nullptr,             nullptr,{ nullptr,             nullptr } },
		{ DMAC_REGISTER_D6_CHCR, DMAC_REGISTER_D6_MADR, DMAC_REGISTER_D6_QWC, DMAC_REGISTER_D6_TADR, nullptr,             nullptr,             nullptr,{ nullptr,             nullptr } },
		{ DMAC_REGISTER_D7_CHCR, DMAC_REGISTER_D7_MADR, DMAC_REGISTER_D7_QWC, nullptr,             nullptr,             nullptr,             nullptr,{ nullptr,             nullptr } },
		{ DMAC_REGISTER_D8_CHCR, DMAC_REGISTER_D8_MADR, DMAC_REGISTER_D8_QWC, nullptr,             nullptr,             nullptr,             DMAC_REGISTER_D8_SADR,{ nullptr,             nullptr } },
		{ DMAC_REGISTER_D9_CHCR, DMAC_REGISTER_D9_MADR, DMAC_REGISTER_D9_QWC, DMAC_REGISTER_D9_TADR, nullptr,             nullptr,             DMAC_REGISTER_D9_SADR,{ nullptr,             nullptr } } },
	DMAC_REGISTER_D_CTRL(std::make_shared<DmacRegisterCtrl_t>()),
	DMAC_REGISTER_D_STAT(std::make_shared<DmacRegisterStat_t>()),
	DMAC_REGISTER_D_PCR(std::make_shared<DmacRegisterPcr_t>()),
	DMAC_REGISTER_D_SQWC(std::make_shared<DmacRegisterSqwc_t>()),
	DMAC_REGISTER_D_RBSR(std::make_shared<DmacRegisterRbsr_t>()),
	DMAC_REGISTER_D_RBOR(std::make_shared<DmacRegisterRbor_t>()),
	DMAC_REGISTER_D_STADR(std::make_shared<DmacRegisterStadr_t>()),
	DMAC_MEMORY_e070(std::make_shared<DeadMMemory_t>(0xF90, "DMAC: DMAC_e070 (reserved)", 0x1000e070)),
	DMAC_MEMORY_F500(std::make_shared<MappedMemory_t>(0x20, "Undocumented: F500", 0x1000f500)),
	DMAC_REGISTER_D_ENABLER(std::make_shared<DmacRegisterEnabler_t>()),
	DMAC_MEMORY_F530(std::make_shared<DeadMMemory_t>(0x60, "DMAC: F530 (reserved)", 0x1000f530)),
	DMAC_REGISTER_D_ENABLEW(std::make_shared<DmacRegisterEnablew_t>()),
	DMAC_MEMORY_F5A0(std::make_shared<DeadMMemory_t>(0x60, "DMAC: F5A0 (reserved)", 0x1000f5A0))
{
}
